### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by waghanza** [sdogruyol/fast-http-server#5]
Hi,

Trying to compile with `crystal` **0.17.4**

``` sh
crystal build --release src/fast-http-server.cr
```

I have a compilation error

``` crystal
Error in ./src/fast-http-server.cr:25: instantiating 'OptionParser:Class#parse!()'
  OptionParser.parse! do |opts|
               ^~~~~~
in /opt/crystal/src/option_parser.cr:56: instantiating 'parse(Array(String))'
    parse(ARGV) { |parser| yield parser }
    ^~~~~
in /opt/crystal/src/option_parser.cr:56: instantiating 'parse(Array(String))'
    parse(ARGV) { |parser| yield parser }
    ^~~~~
in ./src/fast-http-server.cr:25: instantiating 'OptionParser:Class#parse!()'
  OptionParser.parse! do |opts|
               ^~~~~~
in ./src/fast-http-server.cr:30: instantiating 'FastHttpServer#port=(String)'
      FastHttpServer::INSTANCE.port = port
                               ^~~~
in macro 'property' /opt/crystal/src/object.cr:672, line 7:
  1.     
  2.       
  3.         def port
  4.           @port
  5.         end
  6. 
  7.         def port=(@port)
  8.         end
  9.       
 10.     
 11.   
        def port=(@port)
                  ^~~~~
instance variable '@port' of FastHttpServer must be Int32, not String
```

Regards,

PS : I use `v0.4.1`

**Comment by waghanza** [comment]
add pull request !6
